/**
 * Enum para tipos de operador
 * Basado en la tabla de tipos de operador del sistema
 */
export enum TipoOperador {
  AGENTE_NAVES = 'AGENTE_NAVES',
  LINEAS_AEREAS = 'LINEAS_AEREAS',
  ESTIBAS_DESESTIBA = 'ESTIBAS_DESESTIBA',
  PROVEEDOR = 'PROVEEDOR',
  MULTIMODAL = 'MULTIMODAL',
  CARGA = 'CARGA',
  FORWARDER = 'FORWARDER',
  MUDANZAS = 'MUDANZAS',
  ALMACENISTA = 'ALMACENISTA',
  COURIER = 'COURIER',
  AGENTE_ADUANAS = 'AGENTE_ADUANAS',
  AGENTE_CABOTAJE = 'AGENTE_CABOTAJE',
  ENTIDAD_CERTIFICADORA = 'ENTIDAD_CERTIFICADORA',
  RETIRO_GARANTIZADO = 'RETIRO_GARANTIZADO',
  DEPOSITO = 'DEPOSITO',
  ZF = 'ZF',
  OP_CONTENEDOR = 'OP_CONTENEDOR'
}

